### ISSUE TITLE
Readme is incorrect or unclear about how to get metadata

### ISSUE THREAD

**Issue by joshuafarray** [CameraKit/jpegkit-android#5]
Description of getting Width/Height from a JPEG are listed as:

> ### MetaData
> You can currently retrieve a JPEGs width and height. This only decodes the JPEGs header information and is very fast.
> ```
> int width = jpegTransformer.getWidth();
> int height = jpegTransformer.getHeight();
> ```

These methods exist on the  `jpegkit.Jpeg` class, not the `jpegkit.JpegTransformer`.  I'm not sure if that's an oversight in the intended implementation of JpegTransformer, or if the readme should be describing how to get metadata from a Jpeg object.

*Edit:* I just realized that there are other bits that seem to refer to the wrong class:

> ```
> jpegTransformer.crop(cropRect);
> ```

`JpegTransformer` class has `cropWithOffsets(...)` and `cropWithRegion(...)` methods.  `Jpeg` class has the `crop(Rect)` method.

**Comment by austinkettner** [comment]
Thanks @joshuafarray we will look into this!

**Comment by austinkettner** [comment]
Closed as per #8
